kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "fio-standalone.fullname" . }}
spec:
  volumeMode: {{ .Values.pvc.volumeMode | quote }}
  {{- if .Values.pvc.storageClassName }}
  storageClassName: {{ .Values.pvc.storageClassName | quote }}
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.size | quote }}
